Update README.md
SoftwareAG/cumulocity-asset-properties-widget pull request #14
Opened 2023-10-18 07:08 UTC by AmarjyotiSAG

widget installation steps added.

2023-10-18 10:11 UTC, lra-sag requested changes

2023-10-18 10:11 UTC, ghost commented on README.md
> +| 2.0.x               | >= 1018.0.0 | 1.0.0                          |
What is application builder? Why is this added here?

2023-10-18 10:11 UTC, ghost commented on README.md
> +1.	Click on Add extension Packages button in Administration > Ecosystem > Extension, where you can add your widget zip file.
Always make sure to provide exact page and button names. Here for example, the page is Extensions and not Extension, the case of letters in the button Add extension package. What is the val
```suggestion
1.  Navigate to Administration > Ecosystem > Extensions
2.  Click  **Add extension package** to upload the zip file

```
What should be the extension availability?
![image](https://github.com/SoftwareAG/cumulocity-asset-properties-widget/assets/104440299/90a3ca5a-c36f-465e-8b00-e9b4c5c87090)

2023-10-18 10:11 UTC, ghost commented on README.md
> +### To install the widget-plugin in the Custom Cockpit application, follow the steps below:
A plugin can be installed on any custom application with cumulocity dashboard. So we don't have to mention custom Cockpit application.
```suggestion
To install the Asset properties 2.0 widget plugin, you must add the plugin package to the extensions first and then install it on the desired custom application.

#### To add the plugin package to extensions
```

2023-10-18 10:11 UTC, ghost commented on README.md
>  ## Installation
Add a section for downloading the release .zip file as discussed in the call.

2023-10-18 10:11 UTC, ghost commented on README.md
> +2.	If you already have a custom Cockpit application, navigate to its Details page (Administration > Ecosystem > Applications > Cockpit(Custom)) and then to the Plugins tab. Install the Asset properti
```suggestion
#### To install the widget plugin on a custom application
1. Navigate Adminstration > Ecosystem > Applications
2. Click application name to view the application details.
3. Switch to **Plugins** tab, Click **Install plugins**
4. In the resulting dialog, search for Asset properties 2.0 widget, click **Install**


To know more about extensions, see [Administration> Managing applications > Extensions](https://cumulocity.com/guides/users-guide/administration/#extensions) in *User guide*
```

2023-10-18 10:11 UTC, lra-sag commented on README.md
> +4. Now your widget is available in your Cockpit application. Navigate to the dashboard where the newly added widget is available in the list of widgets to add.
Remove these lines and add a note instead
```suggestion
Note: You need a custom application with Cumulocity IoT dashboard to see the widget in action. A quick way to achieve this is by creating a custom Cockpit application.
To create  a custom Cockpit application, follow the steps below:
1. Navigate to Administration > Ecosystem > Applications 
2. click **Add application**. 
3. In the resulting dialog, select the option **Duplicate existing application**. 
4. From the list of applications, select Cockpit (Subscribed). Use the default values and proceed.
```

2023-10-25 05:27 UTC, AmarjyotiSAG commented on README.md
> +1.	Click on Add extension Packages button in Administration > Ecosystem > Extension, where you can add your widget zip file.
extension availability means the allpication availability for sub tenant, you will get more info click on question mark icon.

2023-10-25 05:31 UTC, AmarjyotiSAG commented on README.md
>  ## Installation
yes, once release is done I need to provide release path to download the zip

2023-10-31 07:14 UTC, AmarjyotiSAG commented on README.md
> +| 2.0.x               | >= 1018.0.0 | 1.0.0                          |
incorporated

2023-10-31 07:15 UTC, AmarjyotiSAG commented on README.md
>  ## Installation
release path added.

2023-10-31 08:35 UTC, lra-sag requested changes

2023-10-31 08:35 UTC, lra-sag commented on README.md
> +### Compatible:
```suggestion
### Compatibility:
```

2023-10-31 08:35 UTC, lra-sag commented on README.md
> +Note: You need a custom application with Cumulocity IoT dashboard to see the widget in action. A quick way to achieve this is by creating a custom Cockpit application.
```suggestion


Note: You need a custom application with Cumulocity IoT dashboard to see the widget in action. A quick way to achieve this is by creating a custom Cockpit application.
```

2023-10-31 08:59 UTC, lra-sag approved these changes

2023-10-31 10:38 UTC, spau6 approved these changes

2023-10-31 10:43 UTC, merged