Feature/workflows
SoftwareAG/cumulocity-asset-properties-widget pull request #20
Opened 2023-10-26 14:17 UTC by spau6

Added the CD workflow to include deploy and e2e runs

2023-10-27 08:03 UTC, lra-sag requested changes, later dismissed

2023-10-27 08:03 UTC, ghost commented on .github/workflows/c8y-deploy-action/action.yml
First create a folder called `actions` in .github folder and add the actions there. Even after this change if you have to modify execute access to the script, create a separate action in a different repository and use it.

2023-10-27 08:03 UTC, ghost commented on .github/workflows/widget-cd.yml
> +      - name: Grant permission
Refer previous comment to remove this step

2023-10-31 13:28 UTC, spau6 commented on .github/workflows/c8y-deploy-action/action.yml
added a folder called action and added the action.yml in it. Action is added with permission step

2023-10-31 13:34 UTC, spau6 commented on .github/workflows/widget-cd.yml
> +      - name: Grant permission
done

2023-11-02 07:28 UTC, AmarjyotiSAG approved these changes

2023-11-02 07:47 UTC, dchc01 approved these changes

2023-11-02 07:54 UTC, merged