Feature/complex property selection
SoftwareAG/cumulocity-asset-properties-widget pull request #36
Opened 2023-12-11 09:54 UTC by AmarjyotiSAG

2023-12-19 07:43 UTC, lra-sag requested changes

2023-12-19 07:43 UTC, ghost commented on asset-properties-widget/component/asset-properties-config/asset-property-item-selector/asset-property-item-selector.component.ts
> +  selectOrUnselectChildren(selectedProperty, action){
```suggestion
  selectOrUnselectChildren(selectedProperty, active){
```

2023-12-19 07:43 UTC, ghost commented on asset-properties-widget/component/asset-properties-config/asset-property-item-selector/asset-property-item-selector.component.ts
> +    return constructProperties.concat(constructCustomProperties);
is the requirement to show all simple properties first and then all complex properties?

2023-12-19 07:43 UTC, ghost commented on asset-properties-widget/component/asset-properties-config/asset-property-item-selector/asset-property-item-selector.component.ts
> +    const constructProperties: IManagedObject[] = [];
```suggestion
    const simpleProperties: IManagedObject[] = [];
```

2023-12-19 07:43 UTC, ghost commented on asset-properties-widget/component/asset-properties-config/asset-property-item-selector/asset-property-item-selector.component.ts
> +    const constructCustomProperties: IManagedObject[] = [];
```suggestion
    const complexProperties: IManagedObject[] = [];
```

2023-12-19 07:43 UTC, ghost commented on asset-properties-widget/component/asset-properties-view/asset-properties-view.component.ts
> +            property.active = true;
why is both hide and active are set to true? How can something be active and hidden at the same time?

2023-12-20 11:37 UTC, AmarjyotiSAG commented on asset-properties-widget/component/asset-properties-config/asset-property-item-selector/asset-property-item-selector.component.ts
> +    return constructProperties.concat(constructCustomProperties);
yes, and same behaviour in older property widget also.

2023-12-20 11:49 UTC, AmarjyotiSAG commented on asset-properties-widget/component/asset-properties-view/asset-properties-view.component.ts
> +            property.active = true;
I have changed that flag name isHide to isParentKeySelected, this flag is required when selecting complex property child item key.

2023-12-20 12:37 UTC, lra-sag approved these changes

2023-12-22 10:02 UTC, srinath0707 approved these changes

2023-12-22 11:03 UTC, merged