Device automation
SoftwareAG/cumulocity-asset-properties-widget pull request #42
Opened 2024-03-05 09:03 UTC by aik24

2024-03-11 03:24 UTC, dchc01 requested changes

2024-03-11 03:24 UTC, dchc01 commented on cypress-E2E-tests/cypress/integration/device_property.cy.ts
> +    cy.get(unassignedDevice).click();
Here you can use clickOnAsset command.

2024-03-11 03:24 UTC, dchc01 commented on cypress-E2E-tests/cypress/integration/device_property.cy.ts
> +    cy.contains('DNS 2');
See if you can get the specific element to add assertion.

2024-03-13 11:45 UTC, dchc01 requested changes

2024-03-13 11:45 UTC, dchc01 commented on cypress-E2E-tests/cypress/integration/device_properties_widget.cy.ts
> +      cy.wait('@loadDevices');
Verify the status code.

2024-03-13 12:05 UTC, aik24 commented on cypress-E2E-tests/cypress/integration/device_properties_widget.cy.ts
> +      cy.wait('@loadDevices');
Added

2024-03-13 12:12 UTC, dchc01 approved these changes

2024-03-13 12:42 UTC, AmarjyotiSAG approved these changes

2024-03-13 12:56 UTC, merged