Updated codebase with some fixes.
SoftwareAG/cumulocity-asset-properties-widget pull request #5
Opened 2023-10-10 15:33 UTC by AmarjyotiSAG

Remove some unwanted import and added few fixes.

2023-10-12 10:06 UTC, lra-sag requested changes

2023-10-12 10:06 UTC, ghost commented on asset-properties-widget/component/asset-properties-config/asset-properties.config.component.spec.ts
rename the component file as asset-properties-config.component.spec.ts

2023-10-12 10:33 UTC, AmarjyotiSAG commented on asset-properties-widget/component/asset-properties-config/asset-properties.config.component.spec.ts
modified

2023-10-13 06:15 UTC, lra-sag approved these changes, later dismissed

2023-10-13 06:15 UTC, lra-sag commented on package.json
> +      "description": "Asset properties configuration widget",
```suggestion
      "description": "Asset properties widget",
```

2023-10-13 06:15 UTC, lra-sag commented on package.json
> +      "globalTitle": "Asset properties configuration widget",
```suggestion
      "globalTitle": "Asset properties widget",
```

2023-10-13 06:16 UTC, lra-sag approved these changes

2023-10-13 08:30 UTC, spau6 approved these changes

2023-10-13 08:30 UTC, merged